# Generated by Django 3.2.18 on 2023-02-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20230224_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contamodel',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='contamodel',
            name='salt',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='contamodel',
            name='senha',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='contamodel',
            name='usuario',
            field=models.CharField(default='', max_length=255),
        ),
    ]
